namespace Cucumba.Cheeto.AssaultCube
{
    enum GameMode
    {
		TEAMDEATHMATCH = 0,
		COOPEDIT,
		DEATHMATCH,
		SURVIVOR,
		TEAMSURVIVOR,
		CTF,
		PISTOLFRENZY,
		BOTTEAMDEATHMATCH,
		BOTDEATHMATCH,
		LASTSWISSSTANDING,
		ONESHOTONEKILL,
		TEAMONESHOTONEKILL,
		BOTONESHOTONEKILL,
		HUNTTHEFLAG,
		TEAMKEEPTHEFLAG,
		KEEPTHEFLAG,
		TEAMPF,
		TEAMLSS,
		BOTPISTOLFRENZY,
		BOTLSS,
		BOTTEAMSURVIVOR,
		BOTTEAMONESHOTONEKILL,
		NUM
	}
}
